name: 📅 Daily Pinecone Re-index

on:
  # every day at 2:00 UTC
  schedule:
    - cron: '0 2 * * *'
  # also allow manual trigger
  workflow_dispatch:

jobs:
  reindex:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run Pinecone indexer
        env:
          OPENAI_API_KEY:       ${{ secrets.OPENAI_API_KEY }}
          PINECONE_API_KEY:     ${{ secrets.PINECONE_API_KEY }}
          PINECONE_ENVIRONMENT: ${{ secrets.PINECONE_ENVIRONMENT }}
          PINECONE_INDEX:       ${{ secrets.PINECONE_INDEX }}
          SHOPIFY_SHOP:         ${{ secrets.SHOPIFY_SHOP }}
          SHOPIFY_ADMIN_API_TOKEN: ${{ secrets.SHOPIFY_ADMIN_API_TOKEN }}
        run: node index-docs.js
